name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, zip, bcmath, pdo_mysql
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets with Vite
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r app bootstrap config database public resources routes storage artisan composer.json composer.lock package.json vite.config.js deployment/
          cp -r public/build deployment/public/ || true
          mkdir -p deployment/storage/app/public
          mkdir -p deployment/storage/framework/{sessions,views,cache}
          mkdir -p deployment/storage/logs
          touch deployment/storage/logs/laravel.log
          chmod -R 755 deployment/storage

      - name: Deploy to cPanel
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          source: "deployment/*"
          target: "~/public_html"
          strip_components: 1
          rm: false

      - name: Run post-deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            cd ~/public_html
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear